Extend SWIG-support to include certifier_pb.h. Gen certifier_pb_wrap.cc
Collection of trial changes -- abortive; needs investigation.

- Add certifier_pb.i SWIG-interface file.

Add makefile rules to certifier.mak to:

- Define symbols for SWIG wrappers around interfaces in certifier.pb.h

- Invoke 'swig' after certifier_pb.h has been generated.

Command to run: $ make -f certifier.mak -B -j 8 sharedlib

See this output:
Generating certifier_pb_wrap.cc
swig -Wallkw -v -python -c++ -Wall -interface libcertifier_pb -outdir .. -o ./certifier_pb_wrap.cc ../include/certifier_pb.i

Starting language-specific parse...
../include/certifier.pb.h:39: Warning 314: 'internal' is a C# keyword, renaming to 'internal_'
../include/certifier.pb.h:251: Error: Syntax error in input(1).
make: *** [certifier.mak:159: certifier_pb_wrap.cc] Error 1